---
# The MIT License (MIT)
#
# Copyright (c) 2015 Taio Jia (jiasir) <jiasir@icloud.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

- name: Install the packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine
    - python-heatclient
- name: Configure heat
  template: src=heat.conf.j2 dest=/etc/heat/heat.conf
- name: Populate the Orchestration database
  shell: /bin/sh -c "heat-manage db_sync" heat
- name: Restart the Orchestration services
  service: name={{ item }} state=restarted
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine
- name: Remove the SQLite database file
  file: name=/var/lib/heat/heat.sqlite state=absent
- name: heat-engine autostart
  shell: echo service heat-engine start >> /etc/rc.local
