---
  - name: Install RabbitMQ
    apt: name=rabbitmq-server update_cache=yes
    retries: 5
    delay: 2
  - name: Configure the message broker service
    command: rabbitmqctl change_password guest {{ rabbitmq_guest_password }}
  - name: Enable remote access for the guest account
    template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  - name: Restart the message broker service
    service: name=rabbitmq-server state=restarted