---
- name: install ntp
  apt: name={{ item }} update_cache=yes
  with_items:
    - ntp
  retries: 5
  delay: 2
- name: Update /etc/ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntp service
- name: Delete ntp.conf.dhcp
  file: name=/var/lib/ntp/ntp.conf.dhcp state=absent
- name: Change time zone to Asia Shanghai
  template: src=timezone.j2 dest=/etc/timezone
  notify: Restart crontab