---
- name: install gcc
  apt: name=gcc update_cache=yes
- name: install libpcre3-dev
  apt: name=libpcre3-dev update_cache=no
- name: install zlib1g-dev
  apt: name=zlib1g-dev update_cache=no
- name: install make
  apt: name=make update_cache=no
- name: copy tar ball
  copy: src={{ file_name }} dest=/tmp/{{ file_name }}
- name: extract tar ball
  command: tar zxvf /tmp/{{ file_name }} -C /tmp
- name: configure
  shell: chdir=/tmp/{{ directory_name }}  ./configure
- name: make and make install
  shell: chdir=/tmp/{{ directory_name }} make && make install
- name: copy config file
  template: src=nginx.conf.j2 dest=/usr/local/nginx/conf/nginx.conf
- name: start nginx
  command: /usr/local/nginx/sbin/nginx
